### ISSUE TITLE
Failure to Connect Error

### ISSUE THREAD

**Issue by MrZombor** [DurinHacks/durinvi#1]
Hello,

When using the launcher it seems that it is only half-working. The hotkeys for increasing and decreasing the FOV work, but F2 does not engage an action camera. I also have an error pop-up that says "Failure to connect" - which if I press the confirm button it will shut down LOTRO, but if I don't and leave the pop-up, I can play the game - with just the FOV fix... though there's possible a memory leak or some instability with leaving that error pop-up.

I am playing on the latest update of LOTRO - which I think is 36.2.

**Comment by pkurras** [comment]
Hi,
that may be because the project still has a second branch where I'm working on a special version of the program. Keeping them separate from each other is a bit more complicated, but I'm already planning to rebuild the project and fix everything. In the short term, I'll focus on the bug and try to find and fix it 'quick and dirty' mode. Thanks for opening this issue.

**Comment by pkurras** [comment]
Btw. the connection error is not a bug. It occurs because I'm not including the second program, which connects to a viewer where you can use a map and network-based navigation. That part of the project is simply not ready yet, and it's not problematic that the connection fails there. It's intentional. [Example here](https://www.youtube.com/watch?v=iA8evqLVt8U).

**Comment by pkurras** [comment]
I recommend using this ~~[version](https://github.com/DurinHacks/durinvi/releases/tag/Kheled-z%C3%83%C2%A2ram)~~ for now. It remains compatible for me and supports both features.

**Comment by MrZombor** [comment]
Wonderful! Thank you for the replies - the map and network-based navigation looks really neat.
